### PR TITLE
Correction and simplification

### PR DESCRIPTION
**Pull request by f5bud**
custombootimg.mk simplification and changes in runatboot.sh usbid_init.sh which is used in init.st-ericsson.rc

### CODE REVIEW

**Comment by GarciaLnk** [comment]
Has been this tested?

**Comment by GarciaLnk** [comment]
Seriously how the hell can have been this merged?

**Comment by Nathanael-Mtd** [comment]
It's closed, not merged... (noob)

**Comment by GarciaLnk** [comment]
Oh, yes, sorry, I go back to play SSB u_u

**Comment by Nathanael-Mtd** [comment]
:| ok

**Pull request closed without merging**
